name: Analyze

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - main

jobs:
  analyze_and_test:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.8'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart analyze
        run: flutter analyze